const events = {
  halloween: [
    {
      id: "halloween_001",
      title: "Haunted Trail",
      description:
        "Brave the eerie woods and encounter ghosts, ghouls, and surprises lurking behind every corner. Do you have what it takes to make it to the end?",
      category: "halloween",
      date: "2024-10-25",
      time: "6:00 PM",
      location: "Spooky Forest",
      price: "$12",
      popularity: 379,
      imageLocal: require("../../assets/halloween_seal/seal_haunted_trail_1.png"),
      imageUrl: null,
    },
    {
      id: "halloween_002",
      title: "Witch's Brew Cocktail Party",
      description:
        "Sip spooky-themed drinks, enjoy mystical music, and conjure up a good time with friends at this magical mixology night.",
      category: "halloween",
      date: "2024-10-26",
      time: "8:00 PM",
      location: "The Mystic Tavern",
      price: "$25",
      popularity: 284,
      imageLocal: require("../../assets/halloween_seal/seal_witch_brew_party_3.png"),
      imageUrl: null,
    },
    {
      id: "halloween_003",
      title: "Trick-or-Treak Movie Marathon",
      description:
        "Settle in for a night of Halloween classics, candy galore, and cozy scares under the flickering glow of the big screen.",
      category: "halloween",
      date: "2024-10-27",
      time: "7:00 PM",
      location: "Cinema Hall",
      price: "$15",
      popularity: 139,
      imageLocal: require("../../assets/halloween_seal/seal_haloween_movie_marathon_1.png"),
      imageUrl: null,
    },
    {
      id: "halloween_004",
      title: "Monster Masquerade Ball",
      description:
        "Dress to impress (and terrify!) at this elegant Halloween soirée featuring costumes, dancing, and a prize for the best disguise.",
      category: "halloween",
      date: "2024-10-28",
      time: "9:00 PM",
      location: "Haunted Mansion",
      price: "$30",
      popularity: 128,
      imageLocal: require("../../assets/halloween_seal/seal__masquerade_ball_1.png"),
      imageUrl: null,
    },
    {
      id: "halloween_005",
      title: "Haunted Escape Room Night",
      description:
        "Solve spooky puzzles and uncover the mystery before time runs out in this chilling escape room experience.",
      category: "halloween",
      date: "2024-10-29",
      time: "6:30 PM",
      location: "Escape House",
      price: "$20",
      popularity: 274,
      imageLocal: require("../../assets/halloween_seal/seal_haunted_escape_room_2.png"),
      imageUrl: null,
    },
    {
      id: "halloween_006",
      title: "Zombie Glow Walk",
      description:
        "Join the undead for a glowing nighttime walk through town—complete with eerie lights, music, and post-walk festivities.",
      category: "halloween",
      date: "2024-10-30",
      time: "8:30 PM",
      location: "Downtown Streets",
      price: "$10",
      popularity: 387,
      imageLocal: require("../../assets/halloween_seal/seal_zombie_glow_walk_1.png"),
      imageUrl: null,
    },
    {
      id: "halloween_007",
      title: "Pumpkin Palooza",
      description:
        "Celebrate the season with pumpkin carving, games, and autumn treats. A perfect event for families and Halloween lovers alike.",
      category: "halloween",
      date: "2024-10-31",
      time: "5:00 PM",
      location: "Community Park",
      price: "Free",
      popularity: 152,
      imageLocal: require("../../assets/halloween_seal/seal_pumpkin_palooza_2.png"),
      imageUrl: null,
    },
  ],

  //-----------------------------------------------------------------------------------------------

  f1: [
    {
      id: "f1_001",
      title: "Seal Speed Circuit",
      description:
        "Join us for the annual seal grand prix racing event! Watch daring drivers zoom in Formula 1 race cars, all competing for the legendary golden fish!",
      category: "sports",
      date: "2024-08-12",
      time: "3:00 PM",
      location: "Flipper Raceway",
      price: "$10",
      popularity: 67,
      imageLocal: require("../../assets/F1_seal/Formula 1.png"),
      imageUrl: null,
    },

    {
      id: "f1_002",
      title: "Seal Scramble 6000",
      description:
        "Join the muddy madness as we race, tumble, and flip all while riding dirt bikes!",
      category: "sports",
      date: "2024-08-19",
      time: "1:00 PM",
      location: "Mudflats Arena",
      price: "$5",
      popularity: 20,
      imageLocal: require("../../assets/F1_seal/seal in a dirt bike 2.png"),
      imageUrl: null,
    },

    {
      id: "f1_003",
      title: "Monster Truck Mayhem",
      description:
        "Take the wheel of a monster truck and ride around in this epic arena of chaos! Watch them crush, crash, and flip over obstacles.",
      category: "sports",
      date: "2024-09-02",
      time: "4:00 PM",
      location: "Crusher Coliseum",
      price: "$15",
      popularity: 31,
      imageLocal: require("../../assets/F1_seal/seal going ah 2.png"),
      imageUrl: null,
    },

    {
      id: "f1_004",
      title: "Seal Support Squad",
      description:
        "Nervous about your driving test? Join our seal squad to do practice runs and be confident hitting the road!",
      category: "education",
      date: "2024-07-14",
      time: "9:00 AM",
      location: "Seal DMV Training Lot",
      price: "Free",
      popularity: 7,
      imageLocal: require("../../assets/F1_seal/dmv seal 2.png"),
      imageUrl: null,
    },

    {
      id: "f1_005",
      title: "Tokyo Street Racing",
      description:
        "The streets are alive with speed! Take on Tokyo's toughest routes in this neon lit race track. Watch racers drift, dash, and zoom toward the finish line!",
      category: "sports",
      date: "2024-08-28",
      time: "10:00 PM",
      location: "Neo Tokyo District",
      price: "$25",
      popularity: 27,
      imageLocal: require("../../assets/F1_seal/seal street race 2.png"),
      imageUrl: null,
    },

    {
      id: "f1_006",
      title: "FlipperDome Fury",
      description:
        "Enter the steel sphere of chaos! Watch stunt riders race inside the cage going in loops and doing cool tricks!",
      category: "sports",
      date: "2024-09-10",
      time: "6:00 PM",
      location: "FlipperDome Arena",
      price: "$18",
      popularity: 51,
      imageLocal: require("../../assets/F1_seal/cool seal 2.png"),
      imageUrl: null,
    },

    {
      id: "f1_007",
      title: "SealStyle Showoff",
      description:
        "Watch drivers perform outrageous vehicle tricks and stunts! Who will pull off the coolest trick?",
      category: "sports",
      date: "2024-09-22",
      time: "2:00 PM",
      location: "Showoff Stadium",
      price: "$12",
      popularity: 95,
      imageLocal: require("../../assets/F1_seal/super cool seal 2.png"),
      imageUrl: null,
    },
  ],

  //-----------------------------------------------------------------------------------------------

  thanksgiving: [
    {
      id: "thanksgiving_001",
      title: "Community Potluck Dinner",
      description:
        "Bring your favorite Thanksgiving dish and share a meal with neighbors and friends in a festive, welcoming setting.",
      category: "holiday",
      date: "2024-11-22",
      time: "6:00 PM",
      location: "Community Center Hall",
      price: "Free",
      popularity: 74,
      imageLocal: require("../../assets/thanksgiving_seal/potluck_seal.png"),
      imageUrl: null,
    },
    {
      id: "thanksgiving_002",
      title: "Turkey Trot Fun Run",
      description:
        "Start the day with a healthy 5K or 1-mile walk/run—costumes encouraged and all ages welcome!",
      category: "holiday",
      date: "2024-11-23",
      time: "8:00 AM",
      location: "Town Park Track",
      price: "$5",
      popularity: 29,
      imageLocal: require("../../assets/thanksgiving_seal/fun_run_seals.png"),
      imageUrl: null,
    },
    {
      id: "thanksgiving_003",
      title: "Thanksgiving Craft Fair",
      description:
        "Shop handmade gifts, fall décor, and local goods while supporting small businesses and artisans.",
      category: "holiday",
      date: "2024-11-21",
      time: "10:00 AM",
      location: "Market Plaza",
      price: "Free",
      popularity: 56,
      imageLocal: require("../../assets/thanksgiving_seal/craft_fair_seal.png"),
      imageUrl: null,
    },
    {
      id: "thanksgiving_004",
      title: "Pumpkin Pie Bake-Off",
      description:
        "Bakers compete to create the tastiest pie—come taste the entries and vote for your favorite!",
      category: "holiday",
      date: "2024-11-22",
      time: "3:00 PM",
      location: "Community Kitchen",
      price: "Free",
      popularity: 37,
      imageLocal: require("../../assets/thanksgiving_seal/bake_off_seal.png"),
      imageUrl: null,
    },
    {
      id: "thanksgiving_005",
      title: "Gratitude Tree Activity",
      description:
        "Write what you’re thankful for on a leaf and hang it on the community tree to spread positivity and reflection.",
      category: "holiday",
      date: "2024-11-23",
      time: "1:00 PM",
      location: "Town Square",
      price: "Free",
      popularity: 48,
      imageLocal: require("../../assets/thanksgiving_seal/gratitude_tree_seal.png"),
      imageUrl: null,
    },
    {
      id: "thanksgiving_006",
      title: "Family Game & Movie Night",
      description:
        "Cozy up with board games and a Thanksgiving-themed movie perfect for all ages—popcorn and cider provided.",
      category: "holiday",
      date: "2024-11-22",
      time: "7:00 PM",
      location: "Community Center",
      price: "Free",
      popularity: 58,
      imageLocal: require("../../assets/thanksgiving_seal/family_night_seals.png"),
      imageUrl: null,
    },
    {
      id: "thanksgiving_007",
      title: "Food Drive & Volunteer Day",
      description:
        "Give back by donating canned goods or volunteering to pack Thanksgiving meals for families in need.",
      category: "holiday",
      date: "2024-11-21",
      time: "9:00 AM",
      location: "Community Hall",
      price: "Free",
      popularity: 82,
      imageLocal: require("../../assets/thanksgiving_seal/food_drive_seals.png"),
      imageUrl: null,
    },
  ],

  //-----------------------------------------------------------------------------------------------

  christmas: [
    {
      id: "christmas_001",
      title: "Holiday Market & Hot Cocoa Bar",
      description: "Sip, Snack, and Enjoy the Whimsy of the Lively Spirit!",
      category: "holiday",
      date: "2024-12-15",
      time: "11:00 AM",
      location: "Town Square Market",
      price: "Free",
      popularity: 123,
      imageLocal: require("../../assets/christmas_seal/market_place_seal1.png"),
      imageUrl: null,
    },
    {
      id: "christmas_002",
      title: "Christmas Karaoke",
      description: "Chime Alongside the Sleigh bells! -- One Song at a Time",
      category: "holiday",
      date: "2024-12-18",
      time: "6:00 PM",
      location: "Community Hall",
      price: "Free",
      popularity: 224,
      imageLocal: require("../../assets/christmas_seal/christmas_karaoke1.png"),
      imageUrl: null,
    },
    {
      id: "christmas_003",
      title: "Candle-Making Workshop",
      description: "Light Up the Holidays! -- Literally",
      category: "holiday",
      date: "2024-12-12",
      time: "2:00 PM",
      location: "Craft Studio",
      price: "$10",
      popularity: 89,
      imageLocal: require("../../assets/christmas_seal/candlemaking_seals1.png"),
      imageUrl: null,
    },
    {
      id: "christmas_004",
      title: "Gingerbread House Contest",
      description: "Build it, Break it, Make it Better!",
      category: "holiday",
      date: "2024-12-20",
      time: "4:00 PM",
      location: "Community Center Kitchen",
      price: "Free",
      popularity: 137,
      imageLocal: require("../../assets/christmas_seal/gingerbread_seals1.png"),
      imageUrl: null,
    },
    {
      id: "christmas_005",
      title: "Ornament Dodgeball",
      description: "Duck, Dodge, & Deck the Halls!",
      category: "holiday",
      date: "2024-12-21",
      time: "3:00 PM",
      location: "Gymnasium",
      price: "$5",
      popularity: 159,
      imageLocal: require("../../assets/christmas_seal/dodgeball_seals1.png"),
      imageUrl: null,
    },
    {
      id: "christmas_006",
      title: "Secret Santa Gift Exchange",
      description: "Give a Little, Laugh A Lot!",
      category: "holiday",
      date: "2024-12-22",
      time: "5:00 PM",
      location: "Community Hall",
      price: "Free",
      popularity: 329,
      imageLocal: require("../../assets/christmas_seal/secret_santa_seals1.png"),
      imageUrl: null,
    },
    {
      id: "christmas_007",
      title: "Krampus Escape Room",
      description: "Escape Krampus, Solve Puzzles and Sleigh the Game!",
      category: "holiday",
      date: "2024-12-23",
      time: "6:00 PM",
      location: "Escape Room Arena",
      price: "$15",
      popularity: 284,
      imageLocal: require("../../assets/christmas_seal/escape_room_seals1.png"),
      imageUrl: null,
    },
  ],

  //-----------------------------------------------------------------------------------------------

  sports: [
    {
      id: "sports_001",
      title: "Archery: Seal the Target",
      description:
        "Join us for the ultimate precision competition. Focus, aim, and release in order to hit the bullseye and win a prize!",
      category: "sports",
      date: "2024-09-15",
      time: "10:00 AM",
      location: "Community Archery Range",
      price: "$5",
      popularity: 76,
      imageLocal: require("../../assets/SportsSeal/archery.png"),
      imageUrl: null,
    },
    {
      id: "sports_002",
      title: "Baseball: Fastball Frenzy",
      description:
        "Get into teams and compete in the ultimate baseball game. Players will slide across slippery bases and hit home runs!",
      category: "sports",
      date: "2024-09-20",
      time: "1:00 PM",
      location: "Seal Stadium",
      price: "$10",
      popularity: 272,
      imageLocal: require("../../assets/SportsSeal/baseball.png"),
      imageUrl: null,
    },
    {
      id: "sports_003",
      title: "Basketball: The Seal Slam",
      description:
        "Grab your balls! And get ready to dunk and rule the court in this basketball showdown!",
      category: "sports",
      date: "2024-09-22",
      time: "3:00 PM",
      location: "Community Gymnasium",
      price: "$8",
      popularity: 101,
      imageLocal: require("../../assets/SportsSeal/basketball.png"),
      imageUrl: null,
    },
    {
      id: "sports_004",
      title: "Football: The Seal Bowl",
      description:
        "Get together and tackle your opponents in order to stop your opponent from getting a score. It's the 67th national Seal Bowl!",
      category: "sports",
      date: "2024-09-28",
      time: "5:00 PM",
      location: "Seal Stadium",
      price: "$15",
      popularity: 999,
      imageLocal: require("../../assets/SportsSeal/football.png"),
      imageUrl: null,
    },
    {
      id: "sports_005",
      title: "Hockey: Puck Splashdown",
      description:
        "Skate across the frozen arena and maneuver around the slippery ground!",
      category: "sports",
      date: "2024-10-05",
      time: "2:00 PM",
      location: "Ice Arena",
      price: "$12",
      popularity: 96,
      imageLocal: require("../../assets/SportsSeal/hockey.png"),
      imageUrl: null,
    },
    {
      id: "sports_006",
      title: "Soccer: Seal Strikers",
      description:
        "Get ready to dodge players and score a goal in this fun arena!",
      category: "sports",
      date: "2024-10-10",
      time: "11:00 AM",
      location: "Town Soccer Field",
      price: "$10",
      popularity: 500,
      imageLocal: require("../../assets/SportsSeal/soccer.png"),
      imageUrl: null,
    },
    {
      id: "sports_007",
      title: "Swimming: Seal Surfers",
      description: "Swim across the giant pool of H2O!",
      category: "sports",
      date: "2024-10-12",
      time: "9:00 AM",
      location: "Community Pool",
      price: "$5",
      popularity: 123,
      imageLocal: require("../../assets/SportsSeal/swim.png"),
      imageUrl: null,
    },
  ],
  // Add Thanksgiving, Christmas, Sports, etc.
};

export default events;
